### ISSUE TITLE
I had a problem（Object(...) is not a function） with the call，I hope you can help me with this.

### ISSUE THREAD

**Issue by Aton5859** [MobileChromeApps/cordova-plugin-zip#88]
my code:
that.zip.unzip("file:///data/user/0/app.framework.test/files/www.zip", "file:///data/user/0/app.framework.test/files", (progress) => console.log('Unzipping, ' + Math.round((progress.loaded / progress.total) * 100) + '%'))
        .then((result) => {
          if (result === 0) console.log('SUCCESS');
          if (result === -1) console.log('FAILED');
        });
error message:
"TypeError: Object(...) is not a function
    at Zip.unzip (file:///android_asset/www/build/vendor.js:75159:145)
    at HomePage.webpackJsonp.197.HomePage.unZip (file:///android_asset/www/build/main.js:322:22)
    at Object.eval [as handleEvent] (ng:///AppModule/HomePage.ngfactory.js:145:31)
    at handleEvent (file:///android_asset/www/build/vendor.js:13558:172)
    at callWithDebugContext (file:///android_asset/www/build/vendor.js:15043:42)
    at Object.debugHandleEvent [as handleEvent] (file:///android_asset/www/build/vendor.js:14630:12)
    at dispatchEvent (file:///android_asset/www/build/vendor.js:10007:25)
    at file:///android_asset/www/build/vendor.js:10621:38 
    at HTMLButtonElement.<anonymous> (file:///android_asset/www/build/vendor.js:36330:53)
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:15660)"

Where did I use it incorrectly? I would appreciate your help in answering this question.

**Comment by nimbleit** [comment]
I have the same problem, how can I fixed it?

**Comment by Aton5859** [comment]
Create a new folder and unzip it，the reason why I encountered this problem is that I decompressed the compressed package under the file.dataDirectory path.

**Comment by nimbleit** [comment]
I tried, but failed. Now I try to use another plugin. thanks

**Comment by nimbleit** [comment]
I solved it through this. https://forum.ionicframework.com/t/ionic-native-unzip/60631/4

**Comment by Aton5859** [comment]
Well done!
